---
apiVersion: v1
kind: Pod
metadata:
  name: go-webapp-arm
  labels:
    app: go-webapp-arm
  annotations:
    isEdgeDeployment: "true"
    targetCondition: "tags.building='b43'"
    priority: "15"
    loggingOptions: ""
spec:
  imagePullSecrets:
  - name: docker-secret
  containers:
  - name: go-webapp-arm
    image: azstcr1.azurecr.io/go-webapp-arm:latest
    ports:
      - containerPort: 80
  nodeSelector:
    type: virtual-kubelet
  tolerations:
  - key: azure.com/iotedge
    effect: NoSchedule
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: go-webapp-arm
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {
      "HostConfig": {
        "PortBindings": {
          "80/tcp": [
            {
              "HostPort": "80"
            }
          ]
        }
      }
    }
---
