---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-webapp-arm-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  template:
    metadata:
      name: go-webapp-arm-deployment
      labels:
        app: go-webapp-arm-deployment
      annotations:
        isEdgeDeployment: "true"
        targetCondition: "tags.building='b43'"
        priority: "15"
        loggingOptions: ""
    spec:
      containers:
      - name: go-webapp-arm-deployment
        image: azstcr1.azurecr.io/go-webapp-arm:latest
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: azure.com/iotedge
        effect: NoSchedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "route": "FROM /* INTO $upstream"
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 7200
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-webapp-arm-deployment
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {
      "HostConfig": {
        "PortBindings": {
          "80/tcp": [
            {
              "HostPort": "80"
            }
          ]
        }
      }
    }
---
