---
apiVersion: v1
kind: Pod
metadata:
  name: go-webapp-arm
  labels:
    app: go-webapp-arm
  annotations:
    isEdgeDeployment: "true"
    targetCondition: "tags.building='b43'"
    priority: "15"
    loggingOptions: ""
spec:
  containers:
  - name: go-webapp-arm
    image: azstcr1.azurecr.io/go-webapp-arm:latest
  nodeSelector:
    type: virtual-kubelet
  tolerations:
  - key: azure.com/iotedge
    effect: NoSchedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "route": "FROM /* INTO $upstream"
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 7200
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-webapp-arm
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {
      "HostConfig": {
        "PortBindings": {
          "80/tcp": [
            {
              "HostPort": "80"
            }
          ]
        }
      }
    }
---
