apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kured
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: kured
  namespace: default
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kured        # Must match `--ds-name`
  namespace: default # Must match `--ds-namespace`
spec:
  template:
    metadata:
      labels:
        name: kured
    spec:
      serviceAccountName: kured
      containers:
        - name: kured
          image: quay.io/weaveworks/kured:master-b27aaa1
          imagePullPolicy: Always
          command:
            - /usr/bin/kured
          args:
            - --ds-name=kured
            - --ds-namespace=default
            - --lock-annotation=weave.works/kured-node-lock
            - --period=1h
            - --reboot-sentinel=/var/run/reboot-required
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: hostrun
              mountPath: /var/run
      restartPolicy: Always
      volumes:
        - name: hostrun
          hostPath:
            path: /var/run
