apiVersion: v1
kind: ServiceAccount
metadata:
  name: kured
  namespace: kube-system
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kured
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kured
  namespace: kube-system
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kured
spec:
  template:
    metadata:
      labels:
        name: kured
    spec:
      containers:
        - name: kured
          image: quay.io/weaveworks/kured:1.0.0
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/kured
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: hostrun
              mountPath: /var/run
      restartPolicy: Always
      volumes:
        - name: hostrun
          hostPath:
            path: /var/run
