apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kured
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: kured
    spec:
      containers:
        - name: kured
          image: quay.io/weaveworks/kured:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/kured
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: hostrun
              mountPath: /var/run
      restartPolicy: Always
      volumes:
        - name: hostrun
          hostPath:
            path: /var/run
