apiVersion: v1
kind: Pod
metadata:
  name: hxe-pod-aci
  labels:
    name: hxe-pod-aci
spec:
  restartPolicy: OnFailure
  volumes:
    - name: hxe-config
      azureFile:
        secretName: azure-secret
        shareName: hxe-config
        readOnly: false
  imagePullSecrets:
  - name: docker-secret
  containers:
  - name: hxe-pod-aci
    image: "store/saplabs/hanaexpress:2.00.030.00.20180403.2"
    resources:
      requests:
        memory: 14G
        cpu: 4
    ports:
      - containerPort: 39013
        name: port1
      - containerPort: 39015
        name: port2
      - containerPort: 39017
        name: port3
      - containerPort: 8090
        name: port4
      - containerPort: 39041
        name: port5
      - containerPort: 59013
        name: port6
    args: [ "--agree-to-sap-license", "--dont-check-system", "--passwords-url", "file:///hana/hxeconfig/masterPassword.json" ]
    volumeMounts:
      - name: hxe-config
        mountPath: /hana/hxeconfig
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-hxe-linux
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
