apiVersion: v1
kind: Pod
metadata:
  name: hxe-pod-aci
  labels:
    name: hxe-pod-aci
spec:
  restartPolicy: OnFailure
  volumes:
    - name: hxe-config
      secret:
        defaultMode: 420
        secretName: masterpassword
  imagePullSecrets:
  - name: acr-secret
  containers:
  - name: hxe-pod-aci
    image: "azstcr1.azurecr.io/store/saplabs/hanaexpress:2.00.030.00.20180403.2"
    resources:
      requests:
        memory: 14G
        cpu: 4
      limits:
        memory: 14G
        cpu: 4
    ports:
      - containerPort: 8090
        name: port1
    args: [ "/bin/bash -c '/run_hana --agree-to-sap-license --dont-check-system --passwords-url file:///hana/hxeconfig/password.json'" ]
    volumeMounts:
      - name: hxe-config
        mountPath: /hana/hxeconfig
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-hxe-linux
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
