apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-files
  # The label is used for matching the exact claim
  labels:
    usage: azure-files
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: hxe-config
    shareNamespace: default
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  selector:
    matchLabels:
      usage: azure-files
---
apiVersion: v1
kind: Pod
metadata:
  name: hxe-pod
  labels:
    name: hxe-pod
spec:
  restartPolicy: OnFailure
  volumes:
    - name: hxe-config
      persistentVolumeClaim:
         claimName: azure-files
  imagePullSecrets:
  - name: docker-secret
  containers:
  - name: hxe-container
    image: "store/saplabs/hanaexpress:2.00.022.00.20171211.1"
    ports:
      - containerPort: 39013
        name: port1
      - containerPort: 39015
        name: port2
      - containerPort: 39017
        name: port3
      - containerPort: 8090
        name: port4
      - containerPort: 39041
        name: port5
      - containerPort: 59013
        name: port6
    args: [ "--agree-to-sap-license", "--dont-check-system", "--passwords-url", "file:///hana/hxeconfig/masterPassword.json" ]
    volumeMounts:
      - name: hxe-config
        mountPath: /hana/hxeconfig
