apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tempsensor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      name: tempsensor
      labels:
        app: tempsensor
      annotations:
        isEdgeDeployment: "true"
        targetCondition: "tags.location.country='worldwide' AND tags.location.building='mobile' AND tags.environment='test'"
        priority: "1"
        loggingOptions: ""
    spec:
      containers:
      - name: tempsensor
        image: "microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview"
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: azure.com/iotedge
        effect: NoSchedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "route": "FROM /* INTO $upstream",
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 5
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempsensor
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {
      "HostConfig": {
        "Memory": 52428800
      }
    }
