apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempsensor-asa
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      name: tempsensor-asa
      labels:
        app: tempsensor-asa
      annotations:
        isEdgeDeployment: "true"
        targetCondition: "tags.location.building='mobile' AND tags.environment='test'"
        priority: "1"
        loggingOptions: ""
    spec:
      containers:
      - name: tempsensor-asa
        image: mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
      - name: aks-iot-edge
        image: microsoft/azureiotedge-azure-stream-analytics:1.0.0-preview007
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: azure.com/iotedge
        effect: NoSchedule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgeagent
data:
  desiredProperties: |
    {
      "systemModules": {
        "edgeHub": {
          "env": {
            "OptimizeForPerformance": {
              "value": "false"
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgehub
data:
  desiredProperties: |
    {
      "routes": {
        "telemetryToCloud": "FROM /messages/modules/tempsensor-asa/* INTO $upstream",
        "alertsToCloud": "FROM /messages/modules/aks-iot-edge/* INTO $upstream",
        "alertsToReset": "FROM /messages/modules/aks-iot-edge/* INTO BrokeredEndpoint(\"/modules/tempsensor-asa/inputs/control\")",
        "telemetryToAsa": "FROM /messages/modules/tempsensor-asa/* INTO BrokeredEndpoint(\"/modules/aks-iot-edge/inputs/temperature\")"
      },
      "storeAndForwardConfiguration": {
        "timeToLiveSecs": 5
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempsensor-asa
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-iot-edge
data:
  status: running
  restartPolicy: always
  version: "1.0"
  createOptions: |
    {}
  desiredProperties: |
    {
      "ASAJobInfo": "https://aksiotedgestorage.blob.core.windows.net/asa-container/EdgeJobs/ac9744c8-91d1-4f90-be65-cf5ad593774e/722733ce-0561-40b7-9ad5-03c3c580e18f/ASAJobInfo.txt?sv=2017-04-17&sr=b&sig=rd1%2B7Qs6Cnlvih1HiagQQMm5rnrb7A3U4FODzWux1Gs%3D&st=2018-06-21T06%3A55%3A30Z&se=2021-06-21T07%3A05%3A30Z&sp=r",
      "ASAJobResourceId": "/subscriptions/05499249-2bf5-4767-b121-db90943e363e/resourceGroups/aks-iot-edge/providers/Microsoft.StreamAnalytics/streamingjobs/aks-iot-edge",
      "ASAJobEtag": "a62660a8-8eca-4e1d-979c-b2b02eed62f7"
    }
